# Generated by Django 5.0.6 on 2024-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaapplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinformation',
            name='number_of_entries_required',
            field=models.CharField(max_length=100),
        ),
    ]
