# Generated by Django 5.0.6 on 2024-06-17 08:27

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_remove_photo_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthcertificate',
            name='birth_certificate',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='embassydocument',
            name='embassy_document',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='familyattestation',
            name='family_attestation',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='medical_document',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='nationalid',
            name='national_id',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='otherdocument',
            name='other_document',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='refugeeid',
            name='refugee_id',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='weddingcertificate',
            name='wedding_certificate',
            field=models.ImageField(upload_to=utils.custom_upload_to),
        ),
    ]
