# Generated by Django 5.0.7 on 2024-08-11 12:35

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_birthcertificate_birth_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('marriage_classification', models.CharField(choices=[('1', 'Civil'), ('2', 'Christian'), ('3', 'Muslim'), ('4', 'Hindu'), ('5', 'Customary'), ('6', 'Registered')], default='1', max_length=1)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('marriage_planned_date', models.DateField(blank=True, null=True)),
                ('record_status', models.CharField(choices=[('1', 'Initiated'), ('2', 'Assigned'), ('3', 'In Progress'), ('4', 'Completed'), ('5', 'Cancelled')], default='1', max_length=1)),
                ('officer_notes', models.TextField(blank=True, null=True)),
                ('assigned_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_assigned_marriage', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registered_by', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarriageAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('passport_photo_bridegroom', models.ImageField(upload_to=utils.custom_upload_to)),
                ('passport_photo_bride', models.ImageField(upload_to=utils.custom_upload_to)),
                ('passport_photo_witness1', models.ImageField(upload_to=utils.custom_upload_to)),
                ('passport_photo_witness2', models.ImageField(upload_to=utils.custom_upload_to)),
                ('passport_or_id_bridegroom', models.ImageField(upload_to=utils.custom_upload_to)),
                ('passport_or_id_bride', models.ImageField(upload_to=utils.custom_upload_to)),
                ('passport_or_id_witness1', models.ImageField(upload_to=utils.custom_upload_to)),
                ('passport_or_id_witness2', models.ImageField(upload_to=utils.custom_upload_to)),
                ('lc1_letter', models.ImageField(upload_to=utils.custom_upload_to)),
                ('marriage_related_document_bridegroom', models.ImageField(upload_to=utils.custom_upload_to)),
                ('marriage_related_document_bride', models.ImageField(upload_to=utils.custom_upload_to)),
                ('proof_of_payment', models.ImageField(upload_to=utils.custom_upload_to)),
                ('birth_certificate', models.ImageField(upload_to=utils.custom_upload_to)),
                ('other_document', models.ImageField(upload_to=utils.custom_upload_to)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_registered_by', to=settings.AUTH_USER_MODEL)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attachments.marriagerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
