# Generated by Django 5.0.7 on 2024-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_marriagerecord_marriageattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriagerecord',
            name='marriage_classification',
            field=models.CharField(choices=[('1', 'Civil'), ('2', 'Christian'), ('3', 'Muslim'), ('4', 'Hindu'), ('5', 'Customary'), ('6', 'Registered')], max_length=1, null=True),
        ),
    ]
